/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kopr;

/**
 *
 * @author Hej urcite
 */
public class ClientForm extends javax.swing.JFrame {

    
    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SpustiButton = new javax.swing.JButton();
        PrerusButton = new javax.swing.JButton();
        ZrusButton = new javax.swing.JButton();
        pocetVlakienLabel = new javax.swing.JLabel();
        pocetVlakienTextField = new javax.swing.JTextField();
        kopirovanieProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SpustiButton.setText("Spusti");
        SpustiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpustiButtonActionPerformed(evt);
            }
        });

        PrerusButton.setText("Preruš");

        ZrusButton.setText("Zruš");

        pocetVlakienLabel.setText("Zadaj počet vlákien");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kopirovanieProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SpustiButton)
                        .addGap(79, 79, 79)
                        .addComponent(PrerusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ZrusButton)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(pocetVlakienLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pocetVlakienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pocetVlakienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pocetVlakienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(kopirovanieProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpustiButton)
                    .addComponent(PrerusButton)
                    .addComponent(ZrusButton))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SpustiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpustiButtonActionPerformed
        int pocetVlakien = 1;
        if(!pocetVlakienTextField.getText().equals("")){
            pocetVlakien = Integer.parseInt(pocetVlakienTextField.getText());
        }
        FileClient.pocetVlakien = pocetVlakien;
        int[] velkosti = new int[pocetVlakien];
        // TODO Swingworker
        ProgressBarSwingWorker pbsw = new ProgressBarSwingWorker(kopirovanieProgressBar);
        pbsw.execute();
        FileClient.spusti();
    }//GEN-LAST:event_SpustiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PrerusButton;
    private javax.swing.JButton SpustiButton;
    private javax.swing.JButton ZrusButton;
    private javax.swing.JProgressBar kopirovanieProgressBar;
    private javax.swing.JLabel pocetVlakienLabel;
    private javax.swing.JTextField pocetVlakienTextField;
    // End of variables declaration//GEN-END:variables
}
